mydjangoapp/urls.py
from django.conf.urls import url
from mydjangoapp import views

app_name = 'mydjangoapp'

urlpatterns = [url(r'^$',views.index, name ='index'),
                url(r'^help/$', views.help,name='help'),
                url(r'^user/$', views.users, name='user'),
                url(r'^form/$', views.form_view, name = 'form_page'),
                url(r'^info/$', views.info, name='info')
    ]

mydjangoproject/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from mydjangoapp import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^app/', include('mydjangoapp.urls')),
    url('admin/', admin.site.urls),
]

mydjangoapp/models.py
from django.db import models

class Topic(models.Model):
    top_name = models.CharField(max_length=264,unique=True)

    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class Accesspage(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

mydjangoapp/forms.py
from django import forms
from django.forms.widgets import Widget
from mydjangoapp.models import Accesspage,Topic,Webpage


class forname(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    text = forms.CharField(widget=forms.Textarea)

class newForm(forms.ModelForm):
    class Meta:
        model = Webpage
        fields = "__all__"  

mydjangoapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import forms

from mydjangoapp.models import Accesspage,Webpage,Topic

def form_view(request):
    form = forms.forname
    
    if request.method=="POST":
        form = forms.forname(request.POST)

        if form.is_valid():
            print("Validation success!")
            print('Name: ' + form.cleaned_data['name'])
            print('E-mail: ' + form.cleaned_data['email'])
            print('Text: ' + form.cleaned_data['text'])
    return render(request, 'mydjangoapp/form_page.html',{'form':form})

def index(request):
    my_dir={'inside_me':"Appearing from the django edited text!"}
    return render(request,'mydjangoapp/index.html',context=my_dir)
    

def info(request):
    Webpagelist = Accesspage.objects.order_by('date')
    date_dir={'access_records': Webpagelist}
    return render(request, 'mydjangoapp/info.html',context=date_dir)

def help(request):
    form = forms.newForm
    
    if request.method=="POST":
        form = forms.newForm(request.POST)

        if form.is_valid():
            print("Validation success!")
            form.save(commit=True)
            return index(request)
    return render(request, 'mydjangoapp/help.html',{'form':form})

def users(request):
    company = Webpage.objects.all()
    company_dir={'companies':company}
    return render(request, 'mydjangoapp/users.html',context=company_dir)

templates/mydjangoapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dummy</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Project</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'mydjangoapp:form_page' %}">Form</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'mydjangoapp:user' %}">Users</a>
              </li>
              <li class="nav-item">
                <a class="nav-link " aria-current="page" href="{% url 'mydjangoapp:help' %}">Help</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'mydjangoapp:info' %}">info</a>
              </li>
            </ul>
          </div>
        </div>
    </nav>
    {%block body_block%}
        <p>this is the base.html</p>
    {%endblock%}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

templates/mydjangoapp/form_page.html
<!DOCTYPE html>
{%extends "mydjangoapp/base.html"%}
{% block body_block%}
    <h1>Fill out this form!</h1>
    <div>
        <form method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="submit">
        </form>
    </div>
{% endblock %}

templates/mydjangoapp/help.html
<!DOCTYPE html>
{% extends "mydjangoapp/base.html"%}
{%block body_block%}
    <h1>Help Page!</h1>
    <div>
        <form method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="submit">
        </form>
    </div>
{%endblock%}

templates/mydjangoapp/index.html
<!DOCTYPE html>
{% extends "mydjangoapp/base.html"%}
{%load static%}
{%block body_block%}
<head>
    <link rel="stylesheet" href="{% static 'css/new.css'%}">
</head>
    <h1>this is inside index.html</h1>
    {{ inside_me }}
    <p>this is the picture of ant</p>
    <img src="{% static "images/ant.jpg" %}">
{%endblock%}

templates/mydjangoapp/info.html
<!DOCTYPE html>
{% extends "mydjangoapp/base.html"%}
{% load static%}
{%block body_block%}
    <h1>Information of date accessed on</h1>
    <div class="infotable">
        {% if access_records %}
            <table>
                <thead>
                    <th>Site Name</th>
                    <th>Date Access</th>
                </thead>
            {% for acc in access_records %}
                <tr>
                    <td> {{acc.name}}</td>
                    <td> {{acc.date}}</td>
                </tr>
            {% endfor %}
            </table>
        {% else %}
            <p>NO access record found!</p>
        {% endif %}
    </div>
{%endblock%}

templates/mydjangoapp/users.html
<!DOCTYPE html>
{% extends "mydjangoapp/base.html"%}
{% load static %}
{%block body_block%}
    <h1>List of company names:</h1>
    {% if companies %}
        <ol>
        {% for comp in companies %}
            <li><b>{{ comp.name }}</b>
            <ul><li>Topic: {{comp.topic}}</li></ul>
            <ul><li>Url: {{comp.url}}</li></ul>
            </li>
        {% endfor %}
        </ol>
    {% else %}
        <p> No company found!</p>
    {% endif %}
{%endblock%}